import * as topicsAPI from "./topics";

const blogs = [
  {
    _id: "5b21ca3eeb7f6fbccd471815",
    title: "Terminator",
    topic: { _id: "5b21ca3eeb7f6fbccd471818", name: "Artificial Intelligence" },
    numberInStock: 6,
    dailyRentalRate: 2.5,
    publishDate: "2018-01-03T19:04:28.809Z",
    content: {
      rows: 7,
      coumns: 0,
      images: [],
      text: [
        {
          row: 0,
          column: 0,
          type: "heading",
          value: ["This is subheadiing"],
        },
        {
          row: 1,
          column: 0,
          type: "paragraph",
          value: ["This is paragraph"],
        },
        {
          row: 2,
          column: 0,
          type: "paragraph",
          value: ["This is paragraph"],
        },
        {
          row: 3,
          column: 0,
          type: "image",
          caption: ["This is subheadiing"],
          reference: "",
        },
        {
          row: 4,
          column: 0,
          type: "paragraph",
          value: ["This is paragraph"],
        },
        {
          row: 5,
          column: 0,
          type: "subheading",
          value: ["Conclusion"],
        },
        {
          row: 6,
          column: 0,
          type: "paragraph",
          value: ["This is paragraph"],
        },
      ],
    },
  },
  {
    _id: "5b21ca3eeb7f6fbccd471816",
    title: "Die Hard",
    topic: { _id: "5b21ca3eeb7f6fbccd471818", name: "Artificial Intelligence" },
    numberInStock: 5,
    dailyRentalRate: 2.5,
    publishDate: "2018-01-03T19:04:28.809Z",
    content: {
      rows: 7,
      coumns: 0,
      images: [],
      text: [
        {
          row: 0,
          column: 0,
          type: "heading",
          value: ["This is subheadiing"],
        },
        {
          row: 1,
          column: 0,
          type: "paragraph",
          value: ["This is paragraph"],
        },
        {
          row: 2,
          column: 0,
          type: "paragraph",
          value: ["This is paragraph"],
        },
        {
          row: 3,
          column: 0,
          type: "image",
          caption: ["This is subheadiing"],
          reference: "",
        },
        {
          row: 4,
          column: 0,
          type: "paragraph",
          value: ["This is paragraph"],
        },
        {
          row: 5,
          column: 0,
          type: "subheading",
          value: ["Conclusion"],
        },
        {
          row: 6,
          column: 0,
          type: "paragraph",
          value: ["This is paragraph"],
        },
      ],
    },
  },
  {
    _id: "5b21ca3eeb7f6fbccd471817",
    title: "Get Out",
    topic: { _id: "5b21ca3eeb7f6fbccd471820", name: "Security" },
    numberInStock: 8,
    dailyRentalRate: 3.5,
    publishDate: "2018-01-03T19:04:28.809Z",
    content: {
      rows: 7,
      coumns: 0,
      images: [],
      text: [
        {
          row: 0,
          column: 0,
          type: "heading",
          value: ["This is subheadiing"],
        },
        {
          row: 1,
          column: 0,
          type: "paragraph",
          value: ["This is paragraph"],
        },
        {
          row: 2,
          column: 0,
          type: "paragraph",
          value: ["This is paragraph"],
        },
        {
          row: 3,
          column: 0,
          type: "image",
          caption: ["This is subheadiing"],
          reference: "",
        },
        {
          row: 4,
          column: 0,
          type: "paragraph",
          value: ["This is paragraph"],
        },
        {
          row: 5,
          column: 0,
          type: "subheading",
          value: ["Conclusion"],
        },
        {
          row: 6,
          column: 0,
          type: "paragraph",
          value: ["This is paragraph"],
        },
      ],
    },
  },
  {
    _id: "5b21ca3eeb7f6fbccd471819",
    title: "Trip to Italy",
    topic: { _id: "5b21ca3eeb7f6fbccd471814", name: "Network" },
    numberInStock: 7,
    dailyRentalRate: 3.5,
    publishDate: "2018-01-03T19:04:28.809Z",
    content: {
      rows: 7,
      coumns: 0,
      images: [],
      text: [
        {
          row: 0,
          column: 0,
          type: "heading",
          value: ["This is subheadiing"],
        },
        {
          row: 1,
          column: 0,
          type: "paragraph",
          value: ["This is paragraph"],
        },
        {
          row: 2,
          column: 0,
          type: "paragraph",
          value: ["This is paragraph"],
        },
        {
          row: 3,
          column: 0,
          type: "image",
          caption: ["This is subheadiing"],
          reference: "",
        },
        {
          row: 4,
          column: 0,
          type: "paragraph",
          value: ["This is paragraph"],
        },
        {
          row: 5,
          column: 0,
          type: "subheading",
          value: ["Conclusion"],
        },
        {
          row: 6,
          column: 0,
          type: "paragraph",
          value: ["This is paragraph"],
        },
      ],
    },
  },
  {
    _id: "5b21ca3eeb7f6fbccd47181a",
    title: "Airplane",
    topic: { _id: "5b21ca3eeb7f6fbccd471814", name: "Network" },
    numberInStock: 7,
    dailyRentalRate: 3.5,
    publishDate: "2018-01-03T19:04:28.809Z",
    content: {
      rows: 7,
      coumns: 0,
      images: [],
      text: [
        {
          row: 0,
          column: 0,
          type: "heading",
          value: ["This is subheadiing"],
        },
        {
          row: 1,
          column: 0,
          type: "paragraph",
          value: ["This is paragraph"],
        },
        {
          row: 2,
          column: 0,
          type: "paragraph",
          value: ["This is paragraph"],
        },
        {
          row: 3,
          column: 0,
          type: "image",
          caption: ["This is subheadiing"],
          reference: "",
        },
        {
          row: 4,
          column: 0,
          type: "paragraph",
          value: ["This is paragraph"],
        },
        {
          row: 5,
          column: 0,
          type: "subheading",
          value: ["Conclusion"],
        },
        {
          row: 6,
          column: 0,
          type: "paragraph",
          value: ["This is paragraph"],
        },
      ],
    },
  },
  {
    _id: "5b21ca3eeb7f6fbccd47181b",
    title: "Wedding Crashers",
    topic: { _id: "5b21ca3eeb7f6fbccd471814", name: "Network" },
    numberInStock: 7,
    dailyRentalRate: 3.5,
    publishDate: "2018-01-03T19:04:28.809Z",
    content: {
      rows: 7,
      coumns: 0,
      images: [],
      text: [
        {
          row: 0,
          column: 0,
          type: "heading",
          value: ["This is subheadiing"],
        },
        {
          row: 1,
          column: 0,
          type: "paragraph",
          value: ["This is paragraph"],
        },
        {
          row: 2,
          column: 0,
          type: "paragraph",
          value: ["This is paragraph"],
        },
        {
          row: 3,
          column: 0,
          type: "image",
          caption: ["This is subheadiing"],
          reference: "",
        },
        {
          row: 4,
          column: 0,
          type: "paragraph",
          value: ["This is paragraph"],
        },
        {
          row: 5,
          column: 0,
          type: "subheading",
          value: ["Conclusion"],
        },
        {
          row: 6,
          column: 0,
          type: "paragraph",
          value: ["This is paragraph"],
        },
      ],
    },
  },
  {
    _id: "5b21ca3eeb7f6fbccd47181e",
    title: "Gone Girl",
    topic: { _id: "5b21ca3eeb7f6fbccd471820", name: "Security" },
    numberInStock: 7,
    dailyRentalRate: 4.5,
    publishDate: "2018-01-03T19:04:28.809Z",
    content: {},
  },
  {
    _id: "5b21ca3eeb7f6fbccd47181f",
    title: "The Sixth Sense",
    topic: { _id: "5b21ca3eeb7f6fbccd471820", name: "Security" },
    numberInStock: 4,
    dailyRentalRate: 3.5,
    publishDate: "2018-01-03T19:04:28.809Z",
    content: {},
  },
  {
    _id: "5b21ca3eeb7f6fbccd471821",
    title: "The Avengers",
    topic: { _id: "5b21ca3eeb7f6fbccd471818", name: "Artificial Intelligence" },
    numberInStock: 7,
    dailyRentalRate: 3.5,
    publishDate: "2018-01-03T19:04:28.809Z",
    content: {},
  },
];

export function getBlog(id) {
  return blogs.find((m) => m._id === id);
}
